---
# firewall-specific tasks for strongswan

- name: Enable ip forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Open firewalld protocols for strongSwan
  firewalld:
    rich_rule: "rule protocol value={{ item }} accept"
    permanent: true
    state: enabled
    immediate: yes
  when:
    (use_firewalld is defined and use_firewalld)
  with_items:
    - ah
    - esp

- name: Open firewalld ports for strongSwan
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  when:
    (use_firewalld is defined and use_firewalld)
  with_items:
    - 500/udp
    - 4500/udp

# - name: "Configure firewall rules to allow strongSwan traffic"
#   ufw:
#     direction=in
#     src="{{ item.0.right.address }}"
#     to="{{ item.0.left.address }}"
#     proto="{{ item.1.proto }}"
#     port="{{ item.1.port | default('') }}"
#     rule=allow
#   when:
#     (use_ufw is defined and use_ufw)
#   with_nested:
#     - "{{ strongswan_conn }}"
#     - [ {"proto": udp, "port": 500}, {"proto": esp}, {"proto": ah} ]
#
# # NOTE: This is a temporary override until the IPSec policy roles are in place,
# #       and requires a patched ufw.py script to allow configuration of GRE
# #       protocols.
# - name: "Configure firewall rules to allow GRE traffic for configured hosts"
#   ufw:
#     direction=in
#     src="{{ item.right.address }}"
#     to="{{ item.left.address }}"
#     proto=gre
#     rule=allow
#   when:
#     (item.left.protoport is defined and item.left.protoport == 47) and
#     (use_ufw is defined and use_ufw)
#   with_items:
#     "{{ strongswan_conn }}"
#   tags:
#     - firewall
